/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;
import model.Voucher;
import modelViews.QlKhachHang;
import modelViews.QlVoucher;
import service.khachhangservice.IKhachHangServise;
import service.khachhangservice.impl.KhachHangServise;
import util.DBConnect;
import util.Uhelper;

/**
 *
 * @author bcuon
 */
public class ViewKhachHang extends javax.swing.JPanel {

    private IKhachHangServise _khHangServise = new KhachHangServise();

    public ViewKhachHang() {
        initComponents();
        load(_khHangServise.selectAll());
    }

    private void load(ArrayList<QlKhachHang> ds) {
        DefaultTableModel model = (DefaultTableModel) tblKhachHang.getModel();
        model.setRowCount(0);
        for (QlKhachHang kh : ds) {
            Object[] row = {
                kh.getId(),
                kh.getMaKh(),
                kh.getTenKh(),
                kh.getGioiTinh() ? "Nam" : "Nữ",
                kh.getSdt(),
                kh.getEmail(),
                kh.getDiaChi(),
                kh.getNgaySinh()
            };
            model.addRow(row);
        }

    }

    private void loadCtKh(String maKh) {
        DefaultTableModel model = (DefaultTableModel) tblKhachhangCt.getModel();
        model.setRowCount(0);
        for (HoaDon kh : _khHangServise.selectCtKhachhang(maKh)) {
            Object[] row = {
                kh.getIdKh().getMaKh(),
                kh.getIdKh().getTenKh(),
                kh.getId(),
                kh.getHinhThucThanhToan(),
                kh.getTongTien(),
                kh.getTongTienGiam(),
                kh.getNgayTao()
            };
            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tblChitietKhachHang = new javax.swing.JDialog();
        tabbedPaneCustom2 = new app.view.swing.TabbedPaneCustom();
        jPanel20 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        scrollPaneWin114 = new custome_ui.swing.ScrollPaneWin11();
        tblKhachHangCtt = new rojeru_san.complementos.RSTableMetro();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMakh = new textfield.TextField2();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenkh = new textfield.TextField2();
        txtNgaysinh = new textfield.TextField2();
        jLabel8 = new javax.swing.JLabel();
        txtDiachi = new textfield.TextField2();
        jLabel4 = new javax.swing.JLabel();
        txtsdt = new textfield.TextField2();
        jLabel7 = new javax.swing.JLabel();
        rdoNam = new radio_button.RadioButtonCustom();
        rdoNu = new radio_button.RadioButtonCustom();
        jLabel10 = new javax.swing.JLabel();
        txtemail = new textfield.TextField2();
        btnThem = new app.view.swing.ButtonGradient();
        btnXoa = new app.view.swing.ButtonGradient();
        btnLammoi = new app.view.swing.ButtonGradient();
        bnSua = new app.view.swing.ButtonGradient();
        tblhoadonchitiet = new app.view.swing.TabbedPaneCustom();
        scrollPaneWin115 = new custome_ui.swing.ScrollPaneWin11();
        tblKhachHang = new rojeru_san.complementos.RSTableMetro();
        scrollPaneWin112 = new custome_ui.swing.ScrollPaneWin11();
        scrollPaneWin111 = new custome_ui.swing.ScrollPaneWin11();
        tblKhachhangCt = new rojeru_san.complementos.RSTableMetro();
        btnTimkiem = new app.view.swing.ButtonGradient();
        txtTimkiem = new textfield.TextField2();
        cboLoctheoGT = new app.view.swing.ComboBoxSuggestion();
        jLabel11 = new javax.swing.JLabel();
        btnLammoi1 = new app.view.swing.ButtonGradient();
        btnLammoi2 = new app.view.swing.ButtonGradient();

        tabbedPaneCustom2.setBackground(new java.awt.Color(38, 28, 73));
        tabbedPaneCustom2.setForeground(new java.awt.Color(255, 255, 255));
        tabbedPaneCustom2.setSelectedColor(new java.awt.Color(51, 0, 102));
        tabbedPaneCustom2.setUnselectedColor(new java.awt.Color(38, 32, 78));

        jPanel20.setBackground(new java.awt.Color(38, 28, 73));

        jPanel26.setBackground(new java.awt.Color(38, 28, 73));
        jPanel26.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel27.setBackground(new java.awt.Color(38, 28, 73));
        jPanel27.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblKhachHangCtt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "Mã HD", "Hình thức thanh toán", "Tổng tiền", "Tổng tiền giảm"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachHangCtt.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        tblKhachHangCtt.setColorBordeFilas(new java.awt.Color(153, 153, 153));
        tblKhachHangCtt.setColorBordeHead(new java.awt.Color(153, 153, 153));
        tblKhachHangCtt.setColorFilasBackgound1(new java.awt.Color(204, 204, 204));
        tblKhachHangCtt.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblKhachHangCtt.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblKhachHangCtt.setColorSelBackgound(new java.awt.Color(38, 28, 73));
        tblKhachHangCtt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblKhachHangCtt.setFuenteFilas(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblKhachHangCtt.setFuenteFilasSelect(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblKhachHangCtt.setFuenteHead(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblKhachHangCtt.setRowHeight(40);
        tblKhachHangCtt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangCttMouseClicked(evt);
            }
        });
        scrollPaneWin114.setViewportView(tblKhachHangCtt);

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPaneWin114, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(730, 730, 730))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneWin114, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel27, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel26Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        tabbedPaneCustom2.addTab("Danh sách khách hàng", jPanel20);

        javax.swing.GroupLayout tblChitietKhachHangLayout = new javax.swing.GroupLayout(tblChitietKhachHang.getContentPane());
        tblChitietKhachHang.getContentPane().setLayout(tblChitietKhachHangLayout);
        tblChitietKhachHangLayout.setHorizontalGroup(
            tblChitietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(tblChitietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tblChitietKhachHangLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabbedPaneCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        tblChitietKhachHangLayout.setVerticalGroup(
            tblChitietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
            .addGroup(tblChitietKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tblChitietKhachHangLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(tabbedPaneCustom2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(38, 28, 73));
        jPanel1.setMinimumSize(new java.awt.Dimension(1330, 790));
        jPanel1.setPreferredSize(new java.awt.Dimension(1330, 790));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, -1));

        jPanel2.setBackground(new java.awt.Color(38, 28, 73));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(38, 28, 73));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        jPanel9.setBackground(new java.awt.Color(38, 28, 73));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(38, 28, 73));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mã KH");

        txtMakh.setForeground(new java.awt.Color(0, 0, 0));
        txtMakh.setEnabled(false);
        txtMakh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ngày sinh");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên KH");

        txtTenkh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtNgaysinh.setForeground(new java.awt.Color(0, 0, 0));
        txtNgaysinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNgaysinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaysinhActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SĐT");

        txtDiachi.setForeground(new java.awt.Color(0, 0, 0));
        txtDiachi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        txtsdt.setForeground(new java.awt.Color(0, 0, 0));
        txtsdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtsdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsdtActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Giới tính");

        rdoNam.setBackground(new java.awt.Color(38, 28, 73));
        buttonGroup1.add(rdoNam);
        rdoNam.setForeground(new java.awt.Color(255, 255, 255));
        rdoNam.setText("Nam");
        rdoNam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNamActionPerformed(evt);
            }
        });

        rdoNu.setBackground(new java.awt.Color(38, 28, 73));
        buttonGroup1.add(rdoNu);
        rdoNu.setForeground(new java.awt.Color(255, 255, 255));
        rdoNu.setText("Nữ");
        rdoNu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Địa chỉ");

        txtemail.setForeground(new java.awt.Color(0, 0, 0));
        txtemail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMakh, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(txtTenkh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(61, 61, 61)
                        .addComponent(rdoNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(125, 125, 125)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)))
                .addGap(49, 49, 49)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtsdt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtMakh, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtTenkh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnThem.setForeground(new java.awt.Color(0, 0, 0));
        btnThem.setText("Thêm");
        btnThem.setColor1(new java.awt.Color(255, 255, 255));
        btnThem.setColor2(new java.awt.Color(102, 102, 102));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setForeground(new java.awt.Color(0, 0, 0));
        btnXoa.setText("Xóa");
        btnXoa.setColor1(new java.awt.Color(255, 255, 255));
        btnXoa.setColor2(new java.awt.Color(102, 102, 102));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLammoi.setForeground(new java.awt.Color(0, 0, 0));
        btnLammoi.setText("Làm mới");
        btnLammoi.setColor1(new java.awt.Color(255, 255, 255));
        btnLammoi.setColor2(new java.awt.Color(102, 102, 102));
        btnLammoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        bnSua.setForeground(new java.awt.Color(0, 0, 0));
        bnSua.setText("Sửa");
        bnSua.setColor1(new java.awt.Color(255, 255, 255));
        bnSua.setColor2(new java.awt.Color(102, 102, 102));
        bnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLammoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLammoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1300, 240));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 240));

        tblhoadonchitiet.setBackground(new java.awt.Color(38, 28, 73));
        tblhoadonchitiet.setForeground(new java.awt.Color(255, 255, 255));
        tblhoadonchitiet.setSelectedColor(new java.awt.Color(51, 0, 102));
        tblhoadonchitiet.setUnselectedColor(new java.awt.Color(38, 32, 78));

        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Mã ", "Tên Kh", "Giới tính", "SĐT", "Email", "Địa chỉ", "Ngày sinh"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachHang.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        tblKhachHang.setColorBordeFilas(new java.awt.Color(153, 153, 153));
        tblKhachHang.setColorBordeHead(new java.awt.Color(153, 153, 153));
        tblKhachHang.setColorFilasBackgound1(new java.awt.Color(204, 204, 204));
        tblKhachHang.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblKhachHang.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblKhachHang.setColorSelBackgound(new java.awt.Color(38, 28, 73));
        tblKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblKhachHang.setFuenteFilas(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblKhachHang.setFuenteFilasSelect(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblKhachHang.setFuenteHead(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblKhachHang.setRowHeight(40);
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        scrollPaneWin115.setViewportView(tblKhachHang);

        tblhoadonchitiet.addTab("Thông tin khách hàng", scrollPaneWin115);

        tblKhachhangCt.setAutoCreateRowSorter(true);
        tblKhachhangCt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "Mã hóa đơn", "Hình thức", "Tổng tiền", "Tổng tiền giảm", "Ngày tạo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachhangCt.setColorBackgoundHead(new java.awt.Color(102, 102, 102));
        tblKhachhangCt.setColorBordeFilas(new java.awt.Color(153, 153, 153));
        tblKhachhangCt.setColorBordeHead(new java.awt.Color(153, 153, 153));
        tblKhachhangCt.setColorFilasBackgound1(new java.awt.Color(204, 204, 204));
        tblKhachhangCt.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tblKhachhangCt.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tblKhachhangCt.setColorSelBackgound(new java.awt.Color(38, 28, 73));
        tblKhachhangCt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblKhachhangCt.setFuenteFilas(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblKhachhangCt.setFuenteFilasSelect(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblKhachhangCt.setFuenteHead(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblKhachhangCt.setRowHeight(30);
        tblKhachhangCt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachhangCtMouseClicked(evt);
            }
        });
        scrollPaneWin111.setViewportView(tblKhachhangCt);

        scrollPaneWin112.setViewportView(scrollPaneWin111);

        tblhoadonchitiet.addTab("Chi tiết Khách hàng", scrollPaneWin112);

        jPanel1.add(tblhoadonchitiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 1300, 440));
        tblhoadonchitiet.getAccessibleContext().setAccessibleName("Bnagr khách hàng");

        btnTimkiem.setForeground(new java.awt.Color(0, 0, 0));
        btnTimkiem.setText("Tìm kiếm");
        btnTimkiem.setColor1(new java.awt.Color(255, 255, 255));
        btnTimkiem.setColor2(new java.awt.Color(102, 102, 102));
        btnTimkiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });
        jPanel1.add(btnTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 112, 35));

        txtTimkiem.setForeground(new java.awt.Color(0, 0, 0));
        txtTimkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(txtTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 292, -1));

        cboLoctheoGT.setBackground(new java.awt.Color(38, 28, 73));
        cboLoctheoGT.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cboLoctheoGT.setForeground(new java.awt.Color(255, 255, 255));
        cboLoctheoGT.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));
        cboLoctheoGT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboLoctheoGT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLoctheoGTItemStateChanged(evt);
            }
        });
        cboLoctheoGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoctheoGTActionPerformed(evt);
            }
        });
        jPanel1.add(cboLoctheoGT, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 281, 37));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Lọc");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, -1));

        btnLammoi1.setForeground(new java.awt.Color(0, 0, 0));
        btnLammoi1.setText("Làm mới");
        btnLammoi1.setColor1(new java.awt.Color(255, 255, 255));
        btnLammoi1.setColor2(new java.awt.Color(102, 102, 102));
        btnLammoi1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLammoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoi1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLammoi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnLammoi2.setForeground(new java.awt.Color(0, 0, 0));
        btnLammoi2.setText("Load");
        btnLammoi2.setColor1(new java.awt.Color(255, 255, 255));
        btnLammoi2.setColor2(new java.awt.Color(102, 102, 102));
        btnLammoi2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLammoi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoi2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLammoi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 260, 112, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 790));
    }// </editor-fold>//GEN-END:initComponents

    private QlKhachHang getForm() {
        try {
            QlKhachHang kh = new QlKhachHang();

            // Validate MaNv
            String maKh = generateRandomMa("KH");
            kh.setMaKh(maKh);
            kh.setTenKh(txtTenkh.getText());
            kh.setGioiTinh(rdoNam.isSelected());
            kh.setSdt(txtsdt.getText());
            kh.setEmail(txtemail.getText());
            kh.setDiaChi(txtDiachi.getText());
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

            Date ngaySinh;
            ngaySinh = dateFormat.parse(txtNgaysinh.getText());

            kh.setNgaySinh(ngaySinh);

            return kh;

        } catch (ParseException ex) {
//            Logger.getLogger(ViewKhachHang.class
//                    .getName()).log(Level.SEVERE, null, ex);
        }
        return null;

    }

    private Boolean validateFormKhachHang() {

        if (Uhelper.checkNull(txtTenkh, "Nhập tên khách hàng")) {
            return true;
        }
//        if (Uhelper.checkNull(txtMakh, "Nhập mã")) {
//            return true;
//        }
        if (Uhelper.checkKyTuDacBiet(txtMakh, "Nhập mã chỉ có chữ cái và số")) {
            return true;
        }

        if (Uhelper.checkNull(txtNgaysinh, "Nhập ngày sinh")) {
            return true;
        }

        if (Uhelper.checkNull(txtDiachi, "Nhập địa chỉ")) {
            return true;
        }
        if (Uhelper.checkNull(txtemail, "Nhập địa chỉ")) {
            return true;
        }
        if (Uhelper.checkNull(txtsdt, "Nhập số điện thoại")) {
            return true;
        }
        if (Uhelper.checkSDT(txtsdt, "Nhập số điện thoại đúng định dạng 9-10 số")) {
            return true;
        }
        if (Uhelper.checkEmail(txtemail, "Nhập email đúng định dạng ")) {
            return true;
        }
//        QlKhachHang kh = getForm();
//        String ma = getMa();
//
//        // Kiểm tra xem chuỗi mã có chứa dấu cách hay không
//        if (ma.contains(" ")) {
//            JOptionPane.showMessageDialog(this, "Mã không được chứa dấu cách");
//            return true; // Trả về true để báo là có lỗi
//        }
//        // Sử dụng biểu thức chính quy để kiểm tra dấu cách
//        if (ma.matches(".*\\s.*")) {
//            JOptionPane.showMessageDialog(this, "Mã không được chứa dấu cách");
//            return true; // Trả về true để báo là có lỗi
//        }
        return false;
    }

//    private boolean checkTrung(String ma) {
//        boolean kq = false;//mặc định kết quả là không trùng
//        for (int i = 0; i < tblKhachHang.getRowCount(); i++) {
//            if (tblKhachHang.getValueAt(i, 0).toString().equalsIgnoreCase(ma)) {
//                kq = true;
//            }
//        }
//        return kq;
//    }

    private String generateRandomMa(String ma) {
        int randomNumber = (int) ((Math.random() * 90000) + 10000);
        return ma + randomNumber;
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        if (validateFormKhachHang()) {
            return;
        }
         ArrayList<QlKhachHang> listKH = _khHangServise.selectAll();
        for (QlKhachHang qlkh : listKH) {
            if (qlkh.getSdt().equals(txtsdt.getText())) {
                JOptionPane.showMessageDialog(this, "Trùng SĐT");
                return;

            }
        }
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date d = sdf.parse(txtNgaysinh.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ngày nhập vào không đúng định dạng(yyyy-MM-dd)");
            txtNgaysinh.requestFocus();
            return;
        }
        try {
            QlKhachHang qlKhachHang = getForm();
            if (_khHangServise.insert(qlKhachHang) != null) {
                JOptionPane.showMessageDialog(this, "Thành công");
            } else {
                JOptionPane.showMessageDialog(this, "Thất bại");
            }
            load(_khHangServise.selectAll());
        } catch (Exception e) {
//            e.printStackTrace();
        }

    }//GEN-LAST:event_btnThemActionPerformed

    private void showDetail() {
        try {
            int selectedRow = tblKhachHang.getSelectedRow();
//            txtMakh.setText(tblKhachHang.getValueAt(selectedRow, 1).toString());
            txtTenkh.setText(tblKhachHang.getValueAt(selectedRow, 2).toString());

            String gioiTinh = (String) tblKhachHang.getValueAt(selectedRow, 3);

            if (gioiTinh.equals("Nam")) {
                rdoNam.setSelected(true);
            } else {
                rdoNu.setSelected(true);
            }
            txtsdt.setText(tblKhachHang.getValueAt(selectedRow, 4).toString());
            txtemail.setText(tblKhachHang.getValueAt(selectedRow, 5).toString());
            txtDiachi.setText(tblKhachHang.getValueAt(selectedRow, 6).toString());

            txtNgaysinh.setText(tblKhachHang.getValueAt(selectedRow, 7).toString());

        } catch (Exception e) {
        }

    }


    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try {
            int selectedRow = tblKhachHang.getSelectedRow();
            if (selectedRow < 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để xóa");
                return;
            }

            int confirmation = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không?");
            if (confirmation != JOptionPane.YES_OPTION) {
                return;
            }
            Integer maCanXoa = (Integer) tblKhachHang.getValueAt(selectedRow, 0);

            if (maCanXoa == null) {
                JOptionPane.showMessageDialog(this, "Không có dữ liệu để xóa");
                return;
            }

            if (_khHangServise.delete(maCanXoa) != null) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                load(_khHangServise.selectAll());
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại vì liên quan đến giàng buộc khóa ngoại");
            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_btnXoaActionPerformed
    private String getMa() {
        int row = tblKhachHang.getSelectedRow();
        String ma = tblKhachHang.getValueAt(row, 1).toString();
        return ma;
    }

    private void bnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnSuaActionPerformed
        int selectedRow = tblKhachHang.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng để sửa");
            return;
        }
        QlKhachHang kh = getForm();
        String ma = getMa();
        kh.setMaKh(ma);
        if (validateFormKhachHang()) {
            return;
        }

        if (_khHangServise.update(kh) != null) {
            JOptionPane.showMessageDialog(this, "Thành công");
        } else {
            JOptionPane.showMessageDialog(this, "Thất bại");
        }
        load(_khHangServise.selectAll());
    }//GEN-LAST:event_bnSuaActionPerformed
    private ArrayList<QlKhachHang> getListKhWhenSearch(String input) {

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date date = null;

        ArrayList<QlKhachHang> listKh = new ArrayList<>();
        ArrayList<QlKhachHang> lstByMa = new ArrayList<>();
        ArrayList<QlKhachHang> lstByName = new ArrayList<>();
        if (!input.trim().matches("[0-9]+")) {
            lstByName = _khHangServise.getAllKhByNameKM0(input);
            listKh.addAll(lstByName);
        }

        lstByMa = _khHangServise.getAllKhByMa0(input);
        listKh.addAll(lstByMa);

        if (listKh.size() == 0) {
            load(listKh);
            JOptionPane.showMessageDialog(this, "Không tìm thấy khách hàng");
        } else {
            if (lstByMa.size() != 0) {
                load(_khHangServise.getAllKhByMa0(input));
            }
            if (lstByName.size() != 0) {
                load(_khHangServise.getAllKhByNameKM0(input));
            }

        }
        return listKh;
    }
    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed

        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date date = null;
        String input = txtTimkiem.getText();

        ArrayList<QlKhachHang> listKhachHang = new ArrayList<>();
        ArrayList<QlKhachHang> lstByMa = new ArrayList<>();
        ArrayList<QlKhachHang> lstByName = new ArrayList<>();

        lstByMa = _khHangServise.getAllKhByMa0(input);
        listKhachHang.addAll(lstByMa);
        lstByName = _khHangServise.getAllKhByNameKM0(input);
        listKhachHang.addAll(lstByName);
        if (listKhachHang.size() == 0) {
            load(listKhachHang);
            JOptionPane.showMessageDialog(this, "Không tìm thấy Khách hàng");
        } else {

            if (lstByMa.size() != 0) {
                load(_khHangServise.getAllKhByMa0(input));
            }
            if (lstByName.size() != 0) {
                load(_khHangServise.getAllKhByNameKM0(input));
            }

        }
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void cboLoctheoGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoctheoGTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoctheoGTActionPerformed

    private void tblKhachhangCtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachhangCtMouseClicked
        showDetail();

    }//GEN-LAST:event_tblKhachhangCtMouseClicked
    private void clear() {
        txtTenkh.setText("");
        txtMakh.setText("");
        txtDiachi.setText("");
        txtNgaysinh.setText("");
        txtTimkiem.setText("");
        txtemail.setText("");
        txtsdt.setText("");
    }
    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        clear();
    }//GEN-LAST:event_btnLammoiActionPerformed
    private void loadDataLocGioiTinh() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblKhachHang.getModel();

            Connection connection = DBConnect.getConnection();
            String sql = "SELECT ma, ten, sdt, email, diaChi, gioiTinh, ngaySinh \n"
                    + "FROM KhachHang WHERE gioiTinh = ?";

            boolean gioiTinhValue = "Nam".equals(cboLoctheoGT.getSelectedItem().toString());

            PreparedStatement statement = connection.prepareStatement(sql);
            statement.setBoolean(1, gioiTinhValue);
            ResultSet rs = statement.executeQuery();

            model.setColumnCount(0);
            model.addColumn("Mã Kh");
            model.addColumn("Tên Kh");
            model.addColumn("Giới tính");
            model.addColumn("SDT");
            model.addColumn("Email");
            model.addColumn("Địa chỉ");
            model.addColumn("Ngày sinh");
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("ma"),
                    rs.getString("ten"),
                    rs.getBoolean("gioiTinh") ? "Nam" : "Nữ",
                    rs.getString("sdt"),
                    rs.getString("email"),
                    rs.getString("diaChi"),
                    rs.getDate("ngaySinh")
                });
            }

            statement.clearParameters();
            connection.close();

        } catch (Exception e) {
//            e.printStackTrace();
        }
    }


    private void cboLoctheoGTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLoctheoGTItemStateChanged
        // TODO add your handling code here:
        loadDataLocGioiTinh();
    }//GEN-LAST:event_cboLoctheoGTItemStateChanged

    private void rdoNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNamActionPerformed

    private void txtsdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsdtActionPerformed

    private void txtNgaysinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaysinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaysinhActionPerformed

    private void tblKhachHangCttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangCttMouseClicked
//        int index = tblKhachHang.getSelectedRow();
//        selectedKhachHang = khachHangService.getAllKhachHang().get(index);
    }//GEN-LAST:event_tblKhachHangCttMouseClicked

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked

        int row = this.tblKhachHang.getSelectedRow();
        if (row != -1 && evt.getClickCount() == 2) {
            String maHoaDon = this.tblKhachHang.getValueAt(row, 1).toString();
            this.loadCtKh(maHoaDon);

            this.tblhoadonchitiet.setSelectedIndex(1);
        } else if ((row != -1 && evt.getClickCount() == 1)) {
            showDetail();
        }
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void btnLammoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLammoi1ActionPerformed

    private void btnLammoi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoi2ActionPerformed
        // TODO add your handling code here:
        load(_khHangServise.selectAll());
    }//GEN-LAST:event_btnLammoi2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private app.view.swing.ButtonGradient bnSua;
    private app.view.swing.ButtonGradient btnLammoi;
    private app.view.swing.ButtonGradient btnLammoi1;
    private app.view.swing.ButtonGradient btnLammoi2;
    private app.view.swing.ButtonGradient btnThem;
    private app.view.swing.ButtonGradient btnTimkiem;
    private app.view.swing.ButtonGradient btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private app.view.swing.ComboBoxSuggestion cboLoctheoGT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private radio_button.RadioButtonCustom rdoNam;
    private radio_button.RadioButtonCustom rdoNu;
    private custome_ui.swing.ScrollPaneWin11 scrollPaneWin111;
    private custome_ui.swing.ScrollPaneWin11 scrollPaneWin112;
    private custome_ui.swing.ScrollPaneWin11 scrollPaneWin114;
    private custome_ui.swing.ScrollPaneWin11 scrollPaneWin115;
    private app.view.swing.TabbedPaneCustom tabbedPaneCustom2;
    private javax.swing.JDialog tblChitietKhachHang;
    private rojeru_san.complementos.RSTableMetro tblKhachHang;
    private rojeru_san.complementos.RSTableMetro tblKhachHangCtt;
    private rojeru_san.complementos.RSTableMetro tblKhachhangCt;
    private app.view.swing.TabbedPaneCustom tblhoadonchitiet;
    private textfield.TextField2 txtDiachi;
    private textfield.TextField2 txtMakh;
    private textfield.TextField2 txtNgaysinh;
    private textfield.TextField2 txtTenkh;
    private textfield.TextField2 txtTimkiem;
    private textfield.TextField2 txtemail;
    private textfield.TextField2 txtsdt;
    // End of variables declaration//GEN-END:variables
}
